name: Run Lighthouse plugin on Linux
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install sitespeed.io
      run: |
        cd .. 
        git clone https://github.com/sitespeedio/sitespeed.io.git
        cd sitespeed.io
        npm install -g 
        cd ../plugin-lighthouse
        npm install
    - name: Lint
      run: npm run lint
    - name: Show working dir
      run: pwd
    - name: Run tests using Lighthouse plugin
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/
    - name: Run tests using Lighthouse prescript
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/ --lighthouse.preScript ./test/preScriptTest.js