name: Run Lighthouse plugin on Linux
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install sitespeed.io
      run: |
        npm install sitespeed.io -g
        cd ../plugin-lighthouse
        npm install
    - name: Lint
      run: npm run lint
    - name: Show sitespeed.io version
      run: sitespeed.io --version
    - name: Run tests using Lighthouse plugin
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/
    - name: Run tests using Lighthouse plugin as mobile
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/ --mobile
    - name: Run tests with configuration file
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/ --lighthouse.config ./test/config.js
    - name: Run tests with flag file
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/ --lighthouse.flags ./test/flags.json 
    #- name: Test global install
    #  run: |
    #    npm install -g
    #    sitespeed.io --plugins.add sitespeed.io-plugin-lighthouse --plugins.remove browsertime https://www.sitespeed.io/